<a href="https://colab.research.google.com/github/dhanushchalicheemala/Practice/blob/main/Pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [5]:
tensor1 = torch.randn(2,3)
tensor1

tensor([[ 0.7683, -0.9434,  0.4269],
        [ 0.7011,  0.3620,  0.7800]])

In [6]:
print(torch.zeros(2,4,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [7]:
t1 = torch.arange(10)
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
t1 = t1.reshape(5,2)

In [9]:
t1[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [10]:
t2 = torch.arange(10,20).reshape(5,2)

In [12]:
t1+t2

tensor([[10, 12],
        [14, 16],
        [18, 20],
        [22, 24],
        [26, 28]])